# Generated by Django 2.1.2 on 2018-10-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TxNba1718CgCj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paiming', models.CharField(blank=True, max_length=255, null=True)),
                ('qiuyuan', models.CharField(blank=True, max_length=255, null=True)),
                ('qiudui', models.CharField(blank=True, max_length=255, null=True)),
                ('defen_selected', models.CharField(blank=True, max_length=255, null=True)),
                ('chushou', models.CharField(blank=True, max_length=255, null=True)),
                ('mingzhong', models.CharField(blank=True, max_length=255, null=True)),
                ('chushou3', models.CharField(blank=True, max_length=255, null=True)),
                ('mingzhong3', models.CharField(blank=True, max_length=255, null=True)),
                ('faci', models.CharField(blank=True, max_length=255, null=True)),
                ('falv', models.CharField(blank=True, max_length=255, null=True)),
                ('lanban', models.CharField(blank=True, max_length=255, null=True)),
                ('qlanban', models.CharField(blank=True, max_length=255, null=True)),
                ('hlanban', models.CharField(blank=True, max_length=255, null=True)),
                ('zhugong', models.CharField(blank=True, max_length=255, null=True)),
                ('qiangduan', models.CharField(blank=True, max_length=255, null=True)),
                ('gaimao', models.CharField(blank=True, max_length=255, null=True)),
                ('shiwu', models.CharField(blank=True, max_length=255, null=True)),
                ('fangui', models.CharField(blank=True, max_length=255, null=True)),
                ('changci', models.CharField(blank=True, max_length=255, null=True)),
                ('shangchang', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Tx_nba_1718_cg_cj',
            },
        ),
    ]
