# Generated by Django 2.1.2 on 2018-11-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opperation', '0004_playerinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerinfo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='txnba1516cgcj',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='txnba1516cgqb',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='txnba1516jhcj',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='txnba1516jhqb',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='txnba1516jqcj',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='txnba1516jqqb',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='txnba1617cgcj',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='txnba1617cgqb',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='txnba1617jhcj',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='txnba1617jhqb',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='txnba1617jqcj',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='txnba1617jqqb',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='txnba1718cgcj',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='txnba1718cgqb',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='txnba1718jhcj',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='txnba1718jhqb',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='txnba1718jqcj',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='txnba1718jqqb',
            options={'managed': True},
        ),
    ]
