# Generated by Django 2.1.2 on 2018-12-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_comments_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user_info',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
