# Generated by Django 2.1.2 on 2018-12-24 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181224_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='tt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleid', models.IntegerField(default=100, verbose_name='文章id')),
                ('parse_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='点赞时间')),
                ('parse_user', models.CharField(max_length=100, verbose_name='点赞用户')),
                ('is_True', models.CharField(max_length=20, verbose_name='是否点赞')),
                ('tt', models.CharField(max_length=100, verbose_name='测试')),
            ],
            options={
                'verbose_name': '点赞模块',
                'verbose_name_plural': '点赞模块',
            },
        ),
    ]
