# Generated by Django 2.1.2 on 2018-12-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_tt'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeseageSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mes_txt', models.CharField(max_length=200, verbose_name='消息内容')),
                ('Mes_User', models.CharField(max_length=20, verbose_name='消息对象')),
                ('Mes_time', models.DateTimeField(max_length=20, verbose_name='消息时间')),
                ('is_read', models.IntegerField(max_length=20, verbose_name='是否已经阅读')),
            ],
            options={
                'verbose_name_plural': '站内信息',
                'verbose_name': '站内信息',
            },
        ),
        migrations.DeleteModel(
            name='tt',
        ),
    ]
