# Generated by Django 2.1.2 on 2018-12-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HupuNbaNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fabu_time', models.CharField(blank=True, max_length=255, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('forums_url', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(max_length=225, null=True, verbose_name='评论')),
            ],
            options={
                'managed': False,
                'verbose_name': '虎扑新闻',
                'db_table': 'hupu_nba_news',
                'verbose_name_plural': '虎扑新闻',
            },
        ),
        migrations.CreateModel(
            name='TxVideo',
            fields=[
                ('video_time', models.CharField(blank=True, max_length=255, null=True)),
                ('video_id', models.CharField(blank=True, max_length=255, null=True)),
                ('video_img', models.CharField(blank=True, max_length=255, null=True)),
                ('video_playurl', models.CharField(blank=True, db_column='video_playUrl', max_length=255, null=True)),
                ('video_num', models.CharField(blank=True, max_length=255, null=True)),
                ('video_title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('true_url', models.CharField(blank=True, max_length=255, null=True)),
                ('video_theme', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'verbose_name': '腾讯视频',
                'db_table': 'tx_video',
                'verbose_name_plural': '腾讯视频',
            },
        ),
        migrations.CreateModel(
            name='XlNews',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('detail_url', models.CharField(blank=True, max_length=255, null=True)),
                ('title_time', models.CharField(blank=True, max_length=255, null=True)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'verbose_name': '新浪新闻',
                'db_table': 'xl_news',
                'verbose_name_plural': '新浪新闻',
            },
        ),
        migrations.CreateModel(
            name='ZbbNews',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('detail_url', models.CharField(blank=True, max_length=255, null=True)),
                ('title_time', models.CharField(blank=True, max_length=255, null=True)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'verbose_name': '直播吧新闻',
                'db_table': 'zbb_news',
                'verbose_name_plural': '直播吧新闻',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleID', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
