# Generated by Django 2.1.2 on 2018-12-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_tt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tt',
        ),
    ]
