# Generated by Django 2.1.2 on 2019-01-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_userparse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saicheng',
            fields=[
                ('datatime', models.CharField(blank=True, max_length=255, null=True)),
                ('starttime', models.CharField(blank=True, db_column='startTime', max_length=255, null=True)),
                ('matchname', models.CharField(blank=True, db_column='matchName', max_length=255, null=True)),
                ('link', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('leftlogo', models.CharField(blank=True, db_column='leftLogo', max_length=255, null=True)),
                ('leftname', models.CharField(blank=True, db_column='leftName', max_length=255, null=True)),
                ('rightlogo', models.CharField(blank=True, db_column='rightLogo', max_length=255, null=True)),
                ('rightname', models.CharField(blank=True, db_column='rightName', max_length=255, null=True)),
                ('vsline', models.CharField(blank=True, db_column='VsLine', max_length=255, null=True)),
            ],
            options={
                'verbose_name': '赛程',
                'managed': False,
                'verbose_name_plural': '赛程',
                'db_table': 'saicheng',
            },
        ),
    ]
